### ISSUE TITLE
re-installing system and re-licensing a paddle app on same mac eats up "activations"

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#34]
hello

i just got a mail from a customer. he used our product and then re-installed his OSX installation and tried to re-activate our product. which didn't work out with too-many-activations.

i think activations should be tied to macs (MAC-address) and if someone re-activates a product on a mac where the product was already active previously this should not substract from the "activations". "activations" normally means "the number of allowed concurrent installations or subsequent installations on DIFFERENT macs when forgetting to de-activate".

**Comment by core-code** [comment]
i thought this was fixed but now i've got a customer report that his licenses were used up just by re-installing the system on the same Mac:
![clip_3](https://cloud.githubusercontent.com/assets/1261954/7569917/7f0c690c-f80c-11e4-9ec7-d1bcfac6bb41.png)

**Comment by core-code** [comment]
still getting reports of customers who have used up all their activations just by re-installing on a single mac...

**Comment by tunabelly** [comment]
I'm actually seeing something similar where customers are seeing this after reinstalling OS X on the same Mac.  I also though something related to the MAC address (or another unique value) was being used so the license could be re-instaled on the same Mac without using up another activation.

To be honest, this specific issue is taking up about 10-20% of my support emails.

**Comment by tunabelly** [comment]
I've gotten a few more in the last couple of days.

Here's a quote from a customer: "Last year this happened to me when I was beta testing Yosemite.  Now, it happened to me again beta testing El Capitan.  Every time a new beta version came out, I found it inadequate, but when the next beta came out I installed all my apps in the newer beta to see if they would run.  I just tried Beta 5 and lo and behold, when I  tried to install TG Pro, it said that i had used my serial number too many times."

**Comment by core-code** [comment]
this issue NEEDS to be reopened.

i'm still getting e-mails from customers who have had all their activations used up just be re-installing on the same mac.

paddle, PLEASE have another look at this issue and fix it for real this time.

**Comment by involer** [comment]
Assinging to @avalore.

**Comment by tunabelly** [comment]
I agree, this need to be fixed sooner than later.  I'm also getting a LOT of customer emails about this issue, especially now that some of them are doing fresh installs of El Capitan.

It's eating up a lot of my time and it's frustrating for the paying customers and giving them a bad experience with my apps.

Please fix!

**Comment by tjosten** [comment]
Same here. This issue has high priority for me, I'd even say it is a show stopper for using Paddle.

**Comment by involer** [comment]
We're actively working on this and hope to have a solid fix within the next week.

**Comment by core-code** [comment]
next week gone by, and we are getting mails because of this daily ...

**Comment by involer** [comment]
A fix for this is in the works, and it is a priority, that we get it out as
soon as possible. As we're dealing with system information (our method of
determining machine relies on MAC address) and our SDK has a concept of
both user-wide and system-wide activations, we're making sure the fix is
properly tested (as not to cause sandboxing issues with the use of MAC
address) and works in all cases.
ᐧ

On Wed, Oct 21, 2015 at 6:39 PM, CoreCode <notifications@github.com> wrote:

> next week gone by, and we are getting mails because of this daily ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PaddleHQ/Mac-Framework/issues/34#issuecomment-149973035>
> .
>



-- 
*CEO, Paddle.com*
+44 (0) 7949 380 919

**Comment by core-code** [comment]
great to hear that progress is being made, thanks!

**Comment by tunabelly** [comment]
+1 for working on this since I'm also getting daily emails and some pretty angry customers. I'm really looking forward to seeing this fixed.

**Comment by tunabelly** [comment]
Any update on this?

**Comment by involer** [comment]
We've uncovered what we think to be the root-cause of the incrementing activations on the same system. In it's current state, we check for a match of three parameters to determine if an activation is a duplicate. The license code, email address and a unique identifier for the system.

Although this is by design, it would seem that the use of a different email address during subsequent registrations is more common than initially anticipated. We're updating the duplication rules to ignore the email field so just license and device are accounted for.

Additionally - we're going through older versions of the API to ensure that these are compatible and aren't throwing any unexpected cases into the situation. All of these changes should be out Thursday latest.

In addition to this, for those who are frequently having this issue, we can bulk add to the activation quota of your licenses, to allow for users who have exhausted all activations, and hopefully reduce your support to almost zero upon these API changes being deployed. If you'd like to do this, please email me at christian@paddle.com

**Comment by tunabelly** [comment]
Ok, thanks for the update and the technical details! I'm really looking forward to the change. Out of curiosity will it require an updated SDK?

**Comment by involer** [comment]
It shouldn't require an update, no. Although, we are making some improvements to the way we handle unique systems in an upcoming release that will make this more reliable on older machines.

**Comment by involer** [comment]
This is now fixed and deployed into production.

**Comment by tunabelly** [comment]
Fantastic! This is probably the most excited I've been for a fix in the Paddle SDK.  :-)

**Comment by involer** [comment]
Please let us know if you encounter any issues, but this has been extensively tested and seems to be working great.

**Comment by core-code** [comment]
thanks for fixing this. i'll let you know if we still encounter this.

in any case, this issue shows a deeper problem in paddle. if a user runs out of 'activations', all paddle does is to tell him it doesn't work and offer to purchase another license (!). 

while, with this bug fixed, we will see this less often now, users will still run out of activations, because 99% of the time they forget to 'deactivate' the app on the old mac before moving on to another one. if the same app on the new mac just says 'doesn't work, purchase again' this sucks.

what paddle SHOULD be doing when the user runs out of activations is to show him a list of Macs he has activated the app on, and offer him to 'deactivate' the app on another Mac so that he can activate it on this Mac. this would be miles better than the current experience where every user that runs out of activations has to mail our support.

**Comment by involer** [comment]
We're working on functionality for remote deactivations, once this is live,
we'll be able to add the ability for users to deactivate existing licensed
machines. Otherwise it opens a potential security problem.

Great suggestion though, and we are working on it.

On Thursday, October 29, 2015, CoreCode <notifications@github.com> wrote:

> thanks for fixing this. i'll let you know if we still encounter this.
>
> in any case, this issue shows a deeper problem in paddle. if a user runs
> out of 'activations', all paddle does is to tell him it doesn't work and
> offer to purchase another license (!).
>
> while, with this bug fixed, we will see this less often now, users will
> still run out of activations, because 99% of the time they forget to
> 'deactivate' the app on the old mac before moving on to another one. if the
> same app on the new mac just says 'doesn't work, purchase again' this sucks.
>
> what paddle SHOULD be doing when the user runs out of activations is to
> show him a list of Macs he has activated the app on, and offer him to
> 'deactivate' the app on another Mac so that he can activate it on this Mac.
> this would be miles better than the current experience where every user
> that runs out of activations has to mail our support.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PaddleHQ/Mac-Framework/issues/34#issuecomment-152242077>
> .
>


-- 
*CEO, Paddle.com*
+44 (0) 7949 380 919

**Comment by core-code** [comment]
thanks, great to know this is being worked on
