### ISSUE TITLE
crash in deactivateLicence in v2.2.2

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#61]
we've received a report about our app crashing inside Paddle's deactivateLicence. we have version 2.2.2. embedded. do you know if this crash has been fixed yet?

Application Specific Information:
Crashing on exception: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff8edd37dc __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff95b89052 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff8ecb3e7e -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
3   CoreFoundation                      0x00007fff8ecc8eab +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
4   Paddle                              0x00000001012bccf7 -[PADLicence deactivateLicence:productId:apiKey:vendorId:email:] + 327
5   Paddle                              0x0000000101297806 -[Paddle deactivateLicence] + 406

**Comment by core-code** [comment]
seems this is already reported as issue #45 but not fixed yet. please fix ;)

**Comment by avalore** [comment]
What version of the SDK did you have this reported from? This should have been fixed for recent versions.

**Comment by core-code** [comment]
> What version of the SDK did you have this reported from?

as the bug report headline description mention, 2.2.2

> This should have been fixed for recent versions.

thats exactly what i was asking, whether this already has been fixed.

since issue #45 - which is the exact same thing - has not been marked as resolved i had assumed this issue still exists in trunk

if its already fixed, thanks! which version contains the fix?

**Comment by core-code** [comment]
issue #45 mentions this bug existing in 2.2.1 and 2.2.4 (in addition to 2.2.2 where i've seen it reported)

**Comment by avalore** [comment]
Ok, 2.3+ *should* fix this, just waiting on confirmation. The issue was to do with deactivating older licence styles so didn't show up that often.

**Comment by core-code** [comment]
thanks i'll update to  2.3+
